### ISSUE TITLE
I can not find some file.

### ISSUE THREAD

**Issue by ccjincong** [elijahcole/single-positive-multi-label#11]
Thanks for your great work. 
I don't know how to find the file following file in the Data directory for COCO. 
* `formatted_train_images.npy`
* `formatted_train_labels.npy`
* `formatted_train_labels_obs.npy`
* `formatted_val_images.npy`
* `formatted_val_labels.npy`
* `formatted_val_labels_obs.npy`
 Could you tell me how to find it.

**Comment by ccjincong** [comment]
I know how to find it. Just need to run format_coco.py. Sorry to bother you.

**Comment by elijahcole** [comment]
No worries! Let me know if anything else comes up :)
