### ISSUE TITLE
I can not find some file, the url in \data\REANDME.md is invalid

### ISSUE THREAD

**Issue by Mark-9999** [elijahcole/single-positive-multi-label#15]
Thank you for great work.
I plan to run the code, but I don't know how to get the next file:
* `train_features_imagenet_resnet50.npy`
* `val_features_imagenet_resnet50.npy`
 I think they are the pre-extracted features you provided in \data\REANDME.md, but the URL (https://caltech.box.com/v/single-positive-multi-label) is invalid. Could you give me a new URL? thank you.

**Comment by elijahcole** [comment]
Actually you are right, there is an issue! Those files are hosted on a Caltech-affiliated account that was deactivated after I graduated. The account has been temporarily restored while I work on a long-term solution. Thanks for flagging this!

**Comment by elijahcole** [comment]
For future stability, I've uploaded the data to Zenodo and changed the links in the README.

https://zenodo.org/records/10162606

https://github.com/elijahcole/single-positive-multi-label/commit/89152d52ba59a65d75b19cbe32254a037b557a57
