### ISSUE TITLE
NUS-wide dataset

### ISSUE THREAD

**Issue by xinyu1205** [elijahcole/single-positive-multi-label#4]
Thank you for your nice work, and I want to follow your work. 
For fair comparison, could you please release your single positive dataset especially NUS-wide dataset?

**Comment by elijahcole** [comment]
Done! Thanks for the reminder.

**Comment by xinyu1205** [comment]
Sorry to bother you again, the download link of nus-wide-urls.txt you reported is invalid (http://dl.nextcenter.org/public/nuswide/NUS-WIDE-urls.rar). Can you post a new download link?
