### ISSUE TITLE
Question about the label estimator initialization

### ISSUE THREAD

**Issue by Correr-Zhou** [elijahcole/single-positive-multi-label#5]
Hi, Elijah!

Great work! After reading the source code, I have a question about the label estimator initialization.

In your paper, you say that *you initialize $\theta_{ni}$ from the uniform distribution on $[\sigma^{-1}(0.4), \sigma^{-1}(0.6)]$ when $z_{ni}$ is unobserved.*
However, the corresponding operation in **models.py** is as following:
```python
# initialize unobserved labels:
w = 0.1
q = inverse_sigmoid(0.5 + w)
param_mtx = q * (2 * torch.rand(num_examples, P['num_classes']) - 1) 
```
I am not sure if I didn't understand this code, or if it was just a mistake?

Looking forward to your reply!

Correr Zhou
2021.8.3

**Comment by elijahcole** [comment]
Thanks for the question!

I _think_ the code is correct, but there is a step for the lower endpoint that's not obvious.

The code initializes the entries of `param_mtx` to be drawn from `Uniform(-q, q)`.

The upper endpoint is straightforward: `q = inverse_sigmoid(0.5 + w)`.

The lower endpoint comes from applying log properties to the definition of the inverse sigmoid function: `-q = - inverse_sigmoid(0.5 + w) = - log( (0.5 + w) / (1 - (0.5 + w)) ) = - log( (0.5 + w) / (0.5 - w) ) = log( (0.5 - w) / (0.5 + w) ) = inverse_sigmoid(0.5 - w)`.

Thanks for flagging this, I've made a note to clarify the code. And please re-open this issue if I didn't answer your question or if I got anything wrong!
