### ISSUE TITLE
Question about the label range.

### ISSUE THREAD

**Issue by jingyang2017** [elijahcole/single-positive-multi-label#6]
Hi, Elijah!
Great work! After reading the source code, I have a question about the observed label's range in losses.py.

From my understanding, "label_vec_obs" is in {-1,1} and "label_vec_true" is in {0,1}.
But for losses 'bce' and 'bce_ls' , 'train_set_variant' is set as 'clean' and their label_vec _obs is same as label_vec_true.

However, in 'losses.py' , 
line 35, 48, assert not torch.any(observed_labels == 0), 
line 134   assert torch.min(observed_labels) >= 0

Did I miss anything in observed label generating?

**Comment by elijahcole** [comment]
Good catch! You're absolutely right, it looks like that's a bug which crept in during refactoring. I just pushed a [fix](https://github.com/elijahcole/single-positive-multi-label/commit/0ea84b0587ef802edec04b02926e12bd9461ccfd).
